Repository SweeTenTeam/Docs, pull requests merged in 2024-11, with the labels that each got.

#12 Verbale esterno12 11
  Documents/2 - RTB/Documentazione_Interna/Verbali_Esterni/Verbale_Esterno_2024-12-11.pdf
  Documents/2 - RTB/Documentazione_Interna/Verbali_Esterni/Verbale_Esterno_2024-12-11.typ
  template/document.typ
Labels: documentation

#14 verbale interno 05-11-2024
  documents/2 - RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-05.typ
Labels: documentation

#16 verbale interno 15-11-2024
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-15.typ
Labels: documentation

#24 terminata prima stesura verbale interno 11-18
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-18.pdf
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-18.typ
  template/document.pdf
  template/document.typ
Labels: documentation

#41 Doc/norme di progetto
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
  template/document.typ
Labels: documentation, norme

#49 Stesura del capitolo: Processi Organizzativi - Gestione dei Processi
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, norme

#51 Stesura del capitolo: Processi Primari - Fornitura
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, norme

#52 Stesura del capitolo: Processi Organizzativi
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
  images/Board.png
  images/Roadmap.png
  template/common.typ
Labels: documentation, norme

#56 Stesura del capitolo: Processi Organizzativi - Standard ISO/IEC 9126
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, norme

#58 Stesura del capitolo: Processi Primari - Sviluppo
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
  images/norme/aggregazione.png
  images/norme/associazione.png
  images/norme/attore.png
  images/norme/attore_caso.png
  images/norme/board.png
  images/norme/caso_uso.png
  images/norme/composizione.png
  images/norme/dipendenza.png
  images/norme/estensione.png
  images/norme/generalizzazione_attori.png
  images/norme/generalizzazione_caso_uso.png
  images/norme/generalizzazione_classe.png
  images/norme/inclusione.png
  images/norme/interfaccia.png
  images/norme/roadmap.png
  images/norme/sistema.png
  images/norme/sottocasi.png
  template/common.typ
Labels: documentation, norme

#55 Aggiornato glossario
  documents/2-RTB/Documentazione_Esterna/Glossario.pdf
  documents/2-RTB/Documentazione_Esterna/Glossario.typ
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  template/common.pdf
  template/document.pdf
Labels: documentation

#59 Stesura del capitolo: Metriche di Qualità Del Prodotto
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP

#60 Doc/analisi dei requisiti - verifica versione 0.0.4
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.typ
Labels: documentation

#62 prima stesura verbale interno 28-11-2024
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-28.pdf
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2024-11-28.typ
Labels: documentation, VI

#64 Stesura capitolo: Processi di supporto - Documentazione
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP
