Repository SweeTenTeam/Docs, pull requests merged in 2024-12, with the labels that each got.

#65 Stesura capitolo: Processi di supporto - Gestione della configurazione
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP

#66 Stesura capitoli: Processi di supporto - Verifica e Validazione
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP

#68 Aggiunti UC: Consultazione GH, Jira, Confluence + img - Verifica e Validazione
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.typ
  images/analisi-dei-requisiti/UCConfluence.png
  images/analisi-dei-requisiti/UCGitHub.png
  images/analisi-dei-requisiti/UCJira.png
  template/common.typ
Labels: documentation

#80 Doc/piano di progetto
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.typ
Labels: documentation

#85 Doc/glossario 83
  documents/2-RTB/Documentazione_Esterna/Glossario.pdf
  documents/2-RTB/Documentazione_Esterna/Glossario.typ
Labels: documentation, Glossario

#86 Stesura introduzione e obiettivi di qualità
  documents/2-RTB/Documentazione_Esterna/Piano_di_Qualifica.typ
Labels: documentation

#92 Stesura Primo Periodo del Piano di Progetto
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.pdf
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.typ
  template/document.typ
Labels: PdP
