Repository SweeTenTeam/Docs, pull requests merged in 2025-04, with the labels that each got.

#239 Doc/verbale/esterno 04 01
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Vervale_Esterno_2025-04-01.typ
Labels: documentation, VE

#238 Doc/verbale/interno 04 01
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-04-01.typ
Labels: documentation, VI

#241 Doc/specifica tecnica gui
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.pdf
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/analisi-dei-requisiti/esl.png
  images/analisi-dei-requisiti/jest.png
  images/analisi-dei-requisiti/lucide.jpg
  images/analisi-dei-requisiti/shad.png
  images/specifica-tecnica/Bubble.png
  images/specifica-tecnica/InputForm.png
  images/specifica-tecnica/chatWindow.png
  images/specifica-tecnica/header.png
  images/specifica-tecnica/navbar.png
  images/specifica-tecnica/uml.png
  template/common.pdf
  template/common.typ
  template/document.pdf
Labels: ST

#253 prima stesura verbale
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-25.pdf
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verble_Esterno_2025-04-08.pdf
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verble_Esterno_2025-04-08.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-04-08.pdf
Labels: VE

#250 Doc/specifica tecnica 236
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/specifica-tecnica/chatBotUML.png
  template/common.typ
Labels: ST, PB

#259 Doc/specifica tecnica 242
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/specifica-tecnica/reqDesiderabili.png
  images/specifica-tecnica/reqObbligatori.png
  images/specifica-tecnica/reqOpzionali.png
Labels: documentation, ST, PB

#262 Doc/specifica tecnica 234
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/specifica-tecnica/api-gateway.png
  template/common.typ
Labels: ST

#261 Docs/manuale utente 243
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.pdf
  documents/2-RTB/Lettera_di_Presentazione.pdf
  documents/3-PB/Documentazione_Esterna/Manuale_Utente.pdf
  documents/3-PB/Documentazione_Esterna/Manuale_Utente.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-04.pdf
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-04.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-11.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-18.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-25.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-04-01.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-10.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-17.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-26.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-04-01.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025_02_24.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025_03_03.typ
  images/manuale-utente/char-error.png
  images/manuale-utente/connection-error.png
  images/manuale-utente/empty-history.png
  images/manuale-utente/esempio.png
  images/manuale-utente/input-area.png
  images/manuale-utente/last-updated.png
  images/manuale-utente/load-more.png
  images/manuale-utente/nav-left.png
  images/manuale-utente/nav-right.png
  images/manuale-utente/navbar.png
  images/manuale-utente/server-error.png
  images/manuale-utente/timeout-error.png
  template/common.pdf
  template/common.typ
  template/document.pdf
Labels: MU

#266 Stesura verbale 04-15
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verble_Esterno_2025-04-15.typ
Labels: VE

#260 Doc/specifica tecnica 237.2
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.pdf
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/specifica-tecnica/confluence.png
  images/specifica-tecnica/github_fetch.png
  images/specifica-tecnica/github_store.png
  template/common.typ
Labels: ST

#268 Doc/lettera di presentazione
  documents/3-PB/Lettera_di_Presentazione.typ
Labels: documentation

#270 Approvazione verbali interni per PB
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-02-24.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-03.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-10.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-17.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-26.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-04-01.typ
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-04-08.typ
Labels: PB

#269 modifica changelog, approvaz documento PB
  documents/3-PB/Documentazione_Esterna/Analisi_dei_Requisiti.typ
Labels: documentation, AdR

#264 Stesura finale piano di progetto
  documents/3-PB/Documentazione_Esterna/Piano_di_Progetto.typ
  template/document.typ
Labels: documentation, PdP

#265 Stesura finale piano di qualifica
  documents/3-PB/Documentazione_Esterna/Piano_di_Qualifica.typ
  images/PdQ/AC1.svg
  images/PdQ/BC.svg
  images/PdQ/CC.svg
  images/PdQ/CO1.svg
  images/PdQ/CRD.svg
  images/PdQ/CRO.svg
  images/PdQ/CRV.svg
  images/PdQ/CS.svg
  images/PdQ/CV1.svg
  images/PdQ/EAC1.svg
  images/PdQ/FD.svg
  images/PdQ/GLP1.svg
  images/PdQ/NCR1.svg
  images/PdQ/PTCP.svg
  images/PdQ/PV1.svg
  images/PdQ/QMS1.svg
  images/PdQ/RSI1.svg
  images/PdQ/TE1.svg
  template/common.typ
  template/document.typ
Labels: documentation, PdQ

#275 approvazione per firma
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verble_Esterno_2025-04-08.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verble_Esterno_2025-04-15.typ
  documents/3-PB/Lettera_di_Presentazione.pdf
Labels: documentation

#273 Doc/piano di qualifica
  documents/3-PB/Documentazione_Esterna/Piano_di_Qualifica.typ
  images/PdQ/AC1.svg
  images/PdQ/BC.svg
  images/PdQ/CC.svg
  images/PdQ/CO1.svg
  images/PdQ/CRD.svg
  images/PdQ/CRO.svg
  images/PdQ/CRV.svg
  images/PdQ/CS.svg
  images/PdQ/CV1.svg
  images/PdQ/EAC1.svg
  images/PdQ/FD.svg
  images/PdQ/GLP1.svg
  images/PdQ/NCR1.svg
  images/PdQ/PTCP.svg
  images/PdQ/PV1.svg
  images/PdQ/QMS1.svg
  images/PdQ/RSI1.svg
  images/PdQ/TE1.svg
  template/common.typ
  template/document.typ
Labels: documentation, PdQ
