Repository SweeTenTeam/Docs, pull requests merged in 2025-02, with the labels that each got.

#158 Approvazione per RTB
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP

#155 Doc/piano di qualifica 134
  documents/2-RTB/Documentazione_Esterna/Piano_di_Qualifica.typ
Labels: PdQ

#162 Verbale/interno 02 05
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-02-05.typ
Labels: VI

#161 Stesura sezioni Cruscotto di valutazione della qualità e Valutazione per il miglioramento
  documents/2-RTB/Documentazione_Esterna/Piano_di_Qualifica.typ
  images/PdQ/AC.svg
  images/PdQ/CO.svg
  images/PdQ/CV.svg
  images/PdQ/EAC.svg
  images/PdQ/GLP.svg
  images/PdQ/NCR.svg
  images/PdQ/PV.svg
  images/PdQ/QMS.svg
  images/PdQ/RSI.svg
  images/PdQ/TE.svg
  template/common.typ
Labels: documentation, PdQ

#167 Doc/norme di progetto
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.pdf
  documents/2-RTB/Documentazione_Interna/Norme_di_Progetto.typ
Labels: documentation, NdP

#166 Doc/piano di progetto
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.pdf
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.typ
  template/document.pdf
  template/document.typ
Labels: documentation, PdP

#170 Doc/piano di qualifica
  documents/2-RTB/Documentazione_Esterna/Piano_di_Qualifica.typ
  images/PdQ/AC.svg
  images/PdQ/CO.svg
  images/PdQ/CV.svg
  images/PdQ/EAC.svg
  images/PdQ/GLP.svg
  images/PdQ/NCR.svg
  images/PdQ/PV.svg
  images/PdQ/QMS.svg
  images/PdQ/RSI.svg
  images/PdQ/TE.svg
  template/common.typ
Labels: PdQ

#171 Approvazione Glossario per RTB
  documents/2-RTB/Documentazione_Interna/Glossario.pdf
  documents/2-RTB/Documentazione_Interna/Glossario.typ
  gloss.csv
Labels: documentation, Glossario

#172 stesura verbale esterno 2025-02-14
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.pdf
  documents/2-RTB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-02-14.pdf
  documents/2-RTB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-02-14.typ
  images/verbali/Message.png
  template/common.typ
Labels: documentation
