Repository SweeTenTeam/Docs, pull requests merged in 2025-03, with the labels that each got.

#201 Prima stesura specifica tecnica
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.pdf
  documents/3-PB/Documentazione_Esterna/Specifica_Tecnica.typ
  images/logos/buddy.png
  template/common.typ
Labels: ST

#202 Stesura introduzione Manuale Utente
  documents/3-PB/Documentazione_Esterna/Manuale_Utente.typ
Labels: documentation, MU, PB

#215 Stesura Verbale Interno 2025-03-10
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-10.typ
Labels: documentation, VI, PB

#214 Verbale Esterno 2025-03-11
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-04.pdf
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-04.typ
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-11.typ
Labels: documentation, PB, VE

#224 Stesura verbale - close #223
  documents/3-PB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025-03-17.typ
Labels: documentation, VI, PB

#226 Stesura verbale - close #225
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-18.typ
Labels: documentation, PB, VE

#227 Firma documento
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-18.typ
Labels: documentation, PB, VE

#228 Firma documento
  documents/3-PB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-03-18.typ
Labels: documentation, PB, VE
