Repository SweeTenTeam/Docs, pull requests merged in 2025-01, with the labels that each got.

#90 UC3 and subs
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.pdf
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.typ
  images/analisi-dei-requisiti/UCConfluence.png
  template/common.pdf
  template/common.typ
Labels: documentation, AdR

#110 Prima stesura verbale esterno
  documents/2-RTB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2025-01-02.typ
Labels: documentation

#116 Approvazione
  documents/2-RTB/Documentazione_Esterna/Verbali_Esterni/Verbale_Esterno_2024-12-17.typ
Labels: documentation

#103 Closes #93; Secondo sprint
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.typ
  template/document.typ
Labels: documentation

#111 Doc/analisi dei requisiti 89
  documents/2-RTB/Documentazione_Esterna/Analisi_dei_Requisiti.typ
  images/analisi-dei-requisiti/UC1_RecuperoInfo.png
  images/analisi-dei-requisiti/UC2_InfoJira.png
  images/analisi-dei-requisiti/UCJira.png
  template/common.typ
Labels: documentation, AdR

#117 Verbale/interno 2025 01 06
  documents/2-RTB/Documentazione_Interna/Verbali_Interni/Verbale_Interno_2025_01_06.typ
Labels: VI

#120 Aggiunta sezione "strategie di testing"
  documents/2-RTB/Documentazione_Esterna/Piano_di_Qualifica.typ
Labels: documentation, PdQ

#123 Terzo sprint - close #106
  documents/2-RTB/Documentazione_Esterna/Piano_di_Progetto.typ
Labels: PdP
